### ISSUE TITLE
要是想抓某个位置的微博要怎么改？

### ISSUE THREAD

**Issue by haxianhe** [dataabc/weibo-crawler#1]
例如这个链接下的微博：https://m.weibo.cn/p/100101B2094650D16EA6F4439A?sudaref=m.weibo.cn&display=0&retcode=6102

**Comment by haxianhe** [comment]
已经解决了：将根据user_id直接替换为consignorid就好了

**Comment by Haitons** [comment]
> 已经解决了：将根据user_id直接替换为consignorid就好了

请问consignorid怎么看，可以说详细一点吗？

**Comment by haxianhe** [comment]
> > 已经解决了：将根据user_id直接替换为consignorid就好了
> 
> 请问consignorid怎么看，可以说详细一点吗？

我的需求是抓取excel中各个链接下的微博内容，我的链接都是位置链接，链接中包含了consignorid
![image](https://user-images.githubusercontent.com/14833731/62991911-1479d500-be84-11e9-9a61-7a260eb71380.png)

**Comment by haxianhe** [comment]
> > 已经解决了：将根据user_id直接替换为consignorid就好了
> 
> 请问consignorid怎么看，可以说详细一点吗？

https://github.com/haxianhe/grab-weibo-messages这是我根据我的需求改的脚本，你可以参考一下
