### ISSUE TITLE
mac下报错，Caused by SSLError("Can't con nect to HTTPS URL because the SSL module is not availa ble.")

### ISSUE THREAD

**Issue by zytjs** [dataabc/weibo-crawler#107]
搜了一圈没找到原因，求救。。。

**Comment by dataabc** [comment]
感谢反馈。

我没遇到过这个问题，搜了下，应该是openssl的原因，参考[安装python3.7.4报错Can't connect to HTTPS URL because the SSL module is not available](https://www.jianshu.com/p/f8585da77ed9)。

如果还有问题，欢迎继续讨论

**Comment by zytjs** [comment]
我的版本是对的，，

**Comment by zytjs** [comment]
你知道Certificates.command在mac的哪里吗，运行一下这个貌似就可以了，但是没找到http://www.cdotson.com/2017/01/sslerror-with-python-3-6-x-on-macos-sierra/

**Comment by dataabc** [comment]
不知道。你上面的链接解决的貌似不是这个问题。你可以再参考下<https://blog.51cto.com/13544424/2149473>

**Comment by zytjs** [comment]
好的，谢谢
