### ISSUE TITLE
关于用户信息verified_type返回0

### ISSUE THREAD

**Issue by Kelaxon** [dataabc/weibo-crawler#108]
`weibo.py` 256行代码在返回用户认证类型`verified_type`时，如果info缺省时返回0

https://github.com/dataabc/weibo-crawler/blob/99b7e80666f57d5da5a5792b5fd645cddf0c78a1/weibo.py#L258

但是根据新浪微博的定义规则，0是黄V-个人用户的含义
https://gist.github.com/chen206/7260648#%E8%AE%A4%E8%AF%81%E7%94%A8%E6%88%B7verified-true

建议修改为
```Python
user_info['verified_type'] = info.get('verified_type', None) # None或者其他数字?
```

**Comment by dataabc** [comment]
太感谢了。

非常好的建议，普通用户占大多数，改成-1应该比较合适
```
            user_info['verified_type'] = info.get('verified_type', -1)
```
如果方便，能否以pull request的形式提交这次修改，这样你可以成为本项目的Contributor。因为这是你发现的bug，并且提出了修改方案，想通过这种方式表示感谢。

再次感谢，如果还有其它建议欢迎继续讨论:smile:

**Comment by Kelaxon** [comment]
好的，已提交了～

**Comment by dataabc** [comment]
刚刚发现，你的名字没有出现在Contributors里，可能的原因是通过git提交代码时的邮箱和注册github时的邮箱不一致。网上的解决方法是“在 setting -> email 添加上提交对应的邮箱，验证过后，提交记录就会显示”。

不知道是否可行，这里只是提醒，添不添邮箱都没关系。我只是觉得你帮了这么大的忙却没有出现在Contributors里有点抱歉

**Comment by Kelaxon** [comment]
没事没事～
