### ISSUE TITLE
[userid问题]这次的数字似乎比较大,也出现了同样的问题

### ISSUE THREAD

**Issue by Preshire** [dataabc/weibo-crawler#11]
大概由于微博是比较新注册的? userid比较长, 结果也出现了类似英文个性化域名输入时的错误

> Error:  'statuses_count'
> Traceback (most recent call last):
>   File "weibo.py", line 739, in start
>     self.get_pages()
>   File "weibo.py", line 694, in get_pages
>     page_count = self.get_page_count()
>   File "weibo.py", line 475, in get_page_count
>     weibo_count = self.user['statuses_count']
> KeyError: 'statuses_count'

id是1005055911162580，麻烦大神再看一下，谢谢！

**Comment by dataabc** [comment]
它的id不是1005055911162580，而是5911162580。你可能是通过<https://m.weibo.cn/>获取id的估计，按照README<https://github.com/dataabc/weibo-crawler#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96user_id>获取就可以得到正确的id了，100505是微博自己加的通用前缀，后面的才是id。
