### ISSUE TITLE
[新功能需求]能否爬取具体的发布时间？精确到分钟

### ISSUE THREAD

**Issue by Preshire** [dataabc/weibo-crawler#12]
爬虫无法爬取具体的发布时间（精确到分钟），想问下这个功能能够加上嘛？谢谢！

**Comment by Preshire** [comment]
以及微博id是什么呢？好像和点击时间所进入的微博并不一样。

**Comment by dataabc** [comment]
第一个问题，免cookie版无法精确到分钟。因为<https://m.weibo.cn>只有最近几天的微博才显示到分，其它微博只显示到天。程序只是把它显示的内容爬下来，为了统一格式，都精确到天。<https://weibo.cn>可以显示到分，cookie版是可以精确到分的，如果需要，可以使用[cookie版](https://github.com/dataabc/weiboSpider)；
第二个问题，微博id是微博的唯一标志。对于免cookie版，<https://m.weibo.cn/detail/>+微博id就是这条微博的详情页，如id为4418978359072196的微博，它的详情页就是<https://m.weibo.cn/detail/4418978359072196>;对于cookie版，<https://weibo.cn/comment/>+微博id就是它的评论详情页，如<https://weibo.cn/comment/I7XIfC45K>，此外<https://weibo.cn/repost/>+微博id是它的转发详情页，<https://weibo.cn/attitude/>+微博id是它的点赞详情页
