### ISSUE TITLE
某些用户会爬取失败

### ISSUE THREAD

**Issue by Alphabet1226** [dataabc/weibo-crawler#128]
同样配置和状态下，有的用户可以正常完整爬到（比如1669879400），但有的用户（比如2218081121）爬取会发生以下报错。
![image](https://user-images.githubusercontent.com/51783873/97389945-a3063500-1916-11eb-8fbc-5741515856e6.png)
在 Issue 里看到这是由于速率过快导致，但是我把速率调到很慢依然无解。
![image](https://user-images.githubusercontent.com/51783873/97389993-bf09d680-1916-11eb-8523-5085b2e190e8.png)
我还在不同的时间分别尝试了添加cookie和不添加cookie，都是一样的结果。并且尝试了很多微博账号，同样出现了有的可以爬有的出现这个报错无法爬。

**Comment by dataabc** [comment]
感谢反馈。

现在应该可以正常获取了，如果还有问题欢迎继续讨论。

**Comment by Alphabet1226** [comment]
感谢您的及时回复。
现在已经可以正常获取，问题已解决，为您的修复速度点赞。

**Comment by malagebidi** [comment]
2218081121这个id我试怎么一次也不成功？
