### ISSUE TITLE
尝试抓取bid的结果，但是输出的excel并没有bid

### ISSUE THREAD

**Issue by Preshire** [dataabc/weibo-crawler#13]
能麻烦再看一下嘛？已经更新到最近的版本了，结果还是没有bid的结果。

**Comment by dataabc** [comment]
刚刚测试了一下，不管是爬原创还是全部，都有bid结果，在csv文件里，第一个字段是id，后面紧跟着的就是bid，我用的user_id是1669879400，你可以再试试。如果没有，有其它报错信息吗？

**Comment by dataabc** [comment]
会不会你把cooki版本当成免cookie版了？
cookie版的输出结果中没有bid，因为它的id就是本程序中的bid，同一条微博中，cookie版的id等于免cookie的bid，这样通过bid就能把两个版本的结果关联起来。

**Comment by Preshire** [comment]
经过测试，是比较弱智的问题导致这一情况发生...已解决，非常感谢！
