### ISSUE TITLE
请问下载的图是查看大图后的高清图吗

### ISSUE THREAD

**Issue by zytjs** [dataabc/weibo-crawler#131]

**Comment by dataabc** [comment]
如果你指的是weibo.com上的“查看大图”，那就不是，应该比“查看大图后的高清图片”更清晰。

下载的是“查看原图后的原始图片”，就是点击“查看大图”-->"查看原图"后的原始图片。

**Comment by zytjs** [comment]
那就更好了，谢谢大佬❤️
