### ISSUE TITLE
部分账号某日期（页数）之前数据爬不下来，非IP或权限问题

### ISSUE THREAD

**Issue by Nilbug** [dataabc/weibo-crawler#135]
问：请您指明哪个版本运行出错（github版/PyPi版/全部）？

答：Python file

问：您使用的是否是最新的程序（是/否）？

答：是

问：爬取任意用户都会运行出错吗（是/否）？

答：否，部分用户可以下载所有时段的数据；但特定用户的前面几页的时候没有问题，但是爬到189页以后（2020年6月），之前的数据爬不到，进度条显示正常，数据为空。

问：若只有爬特定微博时才出错，能否提供出错微博的weibo_id或url（非必填）？

答：是，id 7281791597 及其他一些账号。

问：若您已提供出错微博的weibo_id或url，可忽略此内容，否则能否提供出错账号的user_id及您配置的since_date，方便我们定位出错微博（非必填）？

答：user_id：7281791597，since_date：2019-08-01

问：如果方便，请您描述出错详情，最好附上错误提示。

答：我想用weibo-crawler爬取userid为7281791597发布的所有微博。刚开始爬取的时候没有问题，但是日期在2020-06-01前的爬不下来。已确认不是ip问题，已加长睡眠时间，该账户并未设置仅几天可见。烦请解答。谢谢！

**Comment by dataabc** [comment]
感谢反馈。

我也不清楚。看了上面的微博，在190多页就没信息了，不是速度问题，也不是被限，不知道是不是这种微博在多少页就不显示了。之所以继续爬，是因为根据微博数有很多页没爬完，之所以为空，是因为网页上这些页应该也是空。猜测可能是微博数量太多，只展示了一部分。

**Comment by Nilbug** [comment]
谢谢您的回复，网页上这几页不是空的，这些日期前发出的微博都可以看见，确实有点棘手！

**Comment by dataabc** [comment]
在本程序使用的接口是空的，在cookie使用的不是。可以使用[cookie版](https://github.com/dataabc/weiboSpider)，可以获取全部内容。

**Comment by Nilbug** [comment]
太感谢了！
