### ISSUE TITLE
7.定期自动爬取微博 方法二中user_id_list参数问题

### ISSUE THREAD

**Issue by kying-kear** [dataabc/weibo-crawler#141]
定期自动爬取微博 方法二 ：把要爬的用户id写入txt文件，然后再把文件路径赋值给config.json中的user_id_list参数，
在weibo.py中 user_id_list = config['user_id_list.txt'] key值为‘user_id_list.txt’。 config.json中的key为‘user_id_list’。

**Comment by dataabc** [comment]
意思是weibo.py和config.json的key不同吗？

weibo.py就是 user_id_list = config['user_id_list']，不是 user_id_list = config['user_id_list.txt']，是一致的。

如果还有问题，欢迎继续讨论

**Comment by kying-kear** [comment]
哈哈哈，我这边的问题。打扰啦
