### ISSUE TITLE
您好，请教两个问题

### ISSUE THREAD

**Issue by zitup** [dataabc/weibo-crawler#151]
1. 使用 [schedule](https://pypi.org/project/schedule/) 定期执行爬取任务是否可行呢。比如，每天0点爬取昨天的数据
2. write_mode 包含数据库的时候，存储的url可以改成本地下载的图片路径吗

谢谢～

**Comment by dataabc** [comment]
1.我没使用schedule，不清楚。
2.可以。修改weibo.py的write_data方法，这个方法是用来写文件的，默认是先写csv、json和数据库,然后下载图片视频。因为你要改url，应该先下载文件，再修改url，再写数据库。所以你应该调整它们的顺序，下载完文件之后再改成本地的url。
self.weibo存储所有微博，self.weibo[0]为第一条，self.weibo[0]['id']，self.weibo[0]['created_at']是发布日期，如果有图片，图片地址self.weibo[0]['pics']，是字符串，如果有多张以英文逗号分开。第二套微博是self.weibo[1]，以此类推。

本地的图片名是：发表日期+id+‘.jpg’，如果有多张，.jpg前还有序号，从1到图片数。所有图片存储在以用户昵称为名(self.user[''screen_name])的文件夹\img\原创微博图片 中，转发微博（self.weibo[0]['retweet']存在，则self.weibo[0]['retweet']就是被转发的微博，self.weibo[0]['retweet']['id']就是它的id，以此类推）图片在转发微博图片中。

综上，你可以修改write_data。先把文件下载放到前面，再按规律，转为本地url，再写数据库。

如果还有问题，欢迎继续讨论。

**Comment by zitup** [comment]
太详细了，感谢🙏
