### ISSUE TITLE
能否不更新 user_id_list 中的日期

### ISSUE THREAD

**Issue by zitup** [dataabc/weibo-crawler#155]
我是想 since_date 和 user_id_list.txt 一起使用。目前是配置中的 since_date 设为了 1，user_id_list 设为 user_id_list.txt，这样就可以爬取昨天的数据，还可以使用 user_id_list.txt 中的 id 列表，但是程序会自动给列表中的 id 后面加上日期，我想给他注释掉，但是没找到代码在哪块😂

**Comment by dataabc** [comment]
注释掉start的如下代码就行
```
                if self.user_config_file_path and self.user:
                    self.update_user_config_file(self.user_config_file_path)
```
你还要手动删除user_id_list.txt每行的日期，因为只有这样才使用config.json的since_date。

如果还有问题，欢迎继续讨论。

**Comment by zitup** [comment]
感谢，可以了😊
