### ISSUE TITLE
unicodedata.normalize

### ISSUE THREAD

**Issue by liy010** [dataabc/weibo-crawler#164]
https://github.com/dataabc/weibo-crawler/blob/39022f8b9126e86097e9197f98324aa6d7ecd050/weibo.py#L545

这一行可以使用`unicodedata.normalize`来转换，替换\u200b我之前也用过，效果不太理想。
（我爬取使用的是selenium，看到你的才知道我那个太麻烦了，还是直接分析json数据方便）

**Comment by dataabc** [comment]
感谢建议。

给出了更好的方式，如果方便，能否按照上面的方式修改代码并pull request呢？这样您还可以成为本项目的Contributor。
