### ISSUE TITLE
Win系统cmd运行，点击左键暂停后，有些时候（未知什么时候），再次点击右键继续时，会卡住

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weibo-crawler#165]
我使用Win系统cmd运行本爬虫，从目前这个版本开始（之前没有遇到过），如果运行过程中在cmd界面上点击左键，按cmd的规则会暂停程序运行，点击鼠标右键时会继续运行，但是目前版本，点击右键可能出现无反应，爬虫卡住的情况，印象中这个问题只在最近这一个月才出现

**Comment by dataabc** [comment]
可能和网络有关，现在的版本和之前相比，没有增加容易卡住的代码。

**Comment by gudaocode** [comment]
OK，多谢
