### ISSUE TITLE
您好，有什么办法压缩图片吗？

### ISSUE THREAD

**Issue by zitup** [dataabc/weibo-crawler#174]
爬下来的图片供前端展示，一张图片几百 K 到几 M，加载很慢很慢😭，所以想问下，python 有什么办法，在下载到时候把图片压缩一下吗，保存两份图，一份原画质，一份略差的。谢谢

**Comment by dataabc** [comment]
我也没用python压缩过图片。其实把图片url中的large换成orj360，就是压缩后的图片url。修改get_pics方法，把pics里的large换成orj360就可以。

**Comment by zitup** [comment]
好的，我试一下。

然后，我想保存下 微博图片的url 到一个txt之类的文件，请问怎么修改

**Comment by zitup** [comment]
我现在是，直接把下载的原图，传到前端展示。因为图片太大了，我的服务器宽带也才1m，前端展示的很慢😂。

刚看了下 orj360 的图，1.4m的原图，这个画质才50k，太爽了，我可以直接下载这个图，传给前端展示，或者直接传给前端微博的链接展示。

所以现在就想，把图片的链接保存下来，直接给前端展示。如果微博的防盗链严重的话，就得**下载图片给前端展示，然后图片和原链接地址对应起来**

**Comment by dataabc** [comment]
图片和链接是有关系的，如果pics只有一个图片，本地图片名就是 发布日期+微博id，若pics是多张图片，则图片名中还会包括它在微博图片中的序号，这就是它们的关系。int(weibo_info['id'])是微博id，self.standardize_date(weibo_info['created_at'])是发布日期。

**Comment by zitup** [comment]
好的，晚上我研究一下～谢谢

**Comment by zitup** [comment]
谢谢大佬，我已经两个画质都下载了，虽然python写的有点烂吧😂
