### ISSUE TITLE
('Error: ', KeyError('status',))

### ISSUE THREAD

**Issue by scratlzj** [dataabc/weibo-crawler#2]
我爬取博主(1711243680),用的 python2.7, 在Ubuntu中操作, 不断出现如下错误:

```
('Error: ', KeyError('status',))
Traceback (most recent call last):
  File "weibo.py", line 302, in get_one_page
    wb = self.get_one_weibo(w)
  File "weibo.py", line 280, in get_one_weibo
    retweet = self.get_long_weibo(retweet_id)
  File "weibo.py", line 70, in get_long_weibo
    weibo_info = js['status']
KeyError: 'status'
```

倒是可以继续爬,但是会漏掉一些推文.换另一个博主也是同样情况, filter = 0或1 都会出现同样情况.不知道是为什么?不知道是不是跟微博包含视频有关?

**Comment by scratlzj** [comment]
虽然出现这个错误提示,最后还是成功爬完写入了,不过应该是会漏掉些微博.我Google keyerror 错误得到这个[网页](https://realpython.com/python-keyerror/),供您参考.

**Comment by Mantezzy** [comment]
我爬取博主(2001169861),用的 python3.6, pycharm. 
```
Traceback (most recent call last):
  File weibo.py", line 428, in start
    self.get_pages()
Error:  'statuses_count'
  File weibo.py", line 401, in get_pages
    page_count = self.get_page_count()
  File weibo.py", line 313, in get_page_count
    weibo_count = self.user['statuses_count']
KeyError: 'statuses_count'
```

**Comment by dataabc** [comment]
感谢反馈，错误已经修复。原因是某些微博需要登录才可以查看，导致获取失败。目前发现这些特殊微博仅出现在微博详情页，程序只有在发现微博是长微博时才会访问详情页以获取微博全部内容，其它情况只访问微博列表页。目前的解决方案是，发现长微博时尝试访问详情页，如果发现获取失败就从列表页解析该微博。二者的区别主要是详情页可以获取微博正文的全部内容，列表页只能获取正文的部分内容，其它主要信息如点赞、评论、分享等信息没有区别。
如果想要获取长微博正文的全部内容，可以添加在request.get时添加cookie信息，虽然这样就背离里免cookie的主旨。加上cookie后就可以爬取全部微博了，不会漏掉微博。这种需要登录才可以访问的微博数量并不多，大约在5%左右，因为测试的范围较小，不一定准确。如果介意这少量的微博，可以添加cookie解决，否则可以忽略。

**Comment by scratlzj** [comment]
这主要是微博限制过多。谢谢，祝您下半年涨工资。
