### ISSUE TITLE
数据库中的video_url如何查看？

### ISSUE THREAD

**Issue by ch634421335** [dataabc/weibo-crawler#203]
例如
[数据库中某条视频地址](http://f.video.weibocdn.com/ReOOkZ7tlx07MUA6NUMM01041202477J0E010.mp4?label=mp4_hd&template=852x480.25.0&trans_finger=d8257cc71422c9ad30fe69ce9523c87b&Expires=1622435296&ssig=gIukjLK%2FCK&KID=unistore,video)
直接复制到浏览器中提示**访问 f.video.weibocdn.com 的请求遭到拒绝**
请问如何查看存储的视频链接？

- [*] 微博已登录
- [*] 更换浏览器同样不能显示

**Comment by dataabc** [comment]
视频地址不是一直有效的，如果需要建议下载视频到本地。如果还有问题欢迎继续讨论。

**Comment by ch634421335** [comment]
> 视频地址不是一直有效的，如果需要建议下载视频到本地。如果还有问题欢迎继续讨论。

好的，非常感谢回复。
