### ISSUE TITLE
write_mode只配置了json，为什么还是会生成weibodata.db

### ISSUE THREAD

**Issue by TrainTsang** [dataabc/weibo-crawler#209]
只想保存json，并且把图片下载到对应文件夹，并不需要存储sqlite，就像上个版本一样，请问如何设置。

**Comment by TrainTsang** [comment]
line 392
            sqlite_exist = ('sqlite' in self.write_mode) and (
                self.sqlite_exist_file(file_path))

line 419
                if not sqlite_exist:
                    self.insert_file_sqlite(file_path, weibo_id, url,
                                            downloaded.content)

392行判断了，如果用户没有设置sqlite，那么false，这么理解，也不能说错了

但是419直接以false作为结论，再强行下载一次，就不太对了

建议把('sqlite' in self.write_mode) 放在419这里再判断

**Comment by dataabc** [comment]
感谢建议。

这里是我疏忽了，确实应该加上'sqlite' in self.write_mode。不但发现问题，并且给出了解决方案，非常感谢。如果方便，能否以pull request的方式将修改后的代码提交到本项目呢，这样您可以成为本项目的Contirbutor。这只是建议，不强制。如果不方便，我会再两天后自己修改。

再次感谢
