### ISSUE TITLE
图片下载不全: 超出9宫格的微博只能下载前9个

### ISSUE THREAD

**Issue by lszero** [dataabc/weibo-crawler#217]

**Comment by dataabc** [comment]
感谢反馈。可以获取全部图片啊，是不是你使用的不是最新版本？

**Comment by lszero** [comment]
是最新版, 我抓取2020年的微博, 很多超过9张图的都只有9张.

**Comment by dataabc** [comment]
能提供user_id吗，方便调试。

**Comment by lszero** [comment]
可以看看这个 https://weibo.com/u/7494295672, 2020-11-20的微博~

**Comment by dataabc** [comment]
可以获取全部图片啊，你加上cookie看看

**Comment by lszero** [comment]
我已经加了. 我再试试吧, 谢谢~
