### ISSUE TITLE
微博抓取 error

### ISSUE THREAD

**Issue by neallg** [dataabc/weibo-crawler#234]
关于微博抓取的问题，更改“since_date”或指定“query_list”时 -- 不发生抓取。
它看起来像这样："微博爬取完成，共爬取0条微博
信息抓取完毕"
能帮忙解决下吗？

**Comment by dataabc** [comment]
感谢反馈。
since_date让程序爬取发布日期在它之后的微博，如果它是最近的日期，可能没有满足要求的微博，获取0条；query_list要求微博中必需包含它里面的内容，如果不包含，获取0条。是不是存在类似的情况？

**Comment by neallg** [comment]
让我试试这个 🙏
例如：Dear-迪丽热巴
https://weibo.com/u/1669879400
    "since_date": "2018-11-01",
    "query_list": ["每一天"],
    "original_pic_download": 1,
    "retweet_pic_download": 0,
    "original_video_download": 1,
    "retweet_video_download": 0,
应该有4张图片和1个视频？

**Comment by dataabc** [comment]
这个需要添加有效cookie，添上就可以了。

**Comment by neallg** [comment]
更新了 cookie，工作正常。谢谢！

这是否意味着我需要更频繁地更新 cookie？
上一个 cookie 一周前更新。

**Comment by dataabc** [comment]
这个好像看账号，不同cookie有效期不一样。

**Comment by neallg** [comment]
明白了，非常感谢！

**Comment by neallg** [comment]
明白了，非常感谢！
