### ISSUE TITLE
被ban了 或者 user_id_list参数错误

### ISSUE THREAD

**Issue by YummyToolman** [dataabc/weibo-crawler#256]
设置user id list，爬一段时间就会出现这个错误并中止程序，能否遇到错误id时就跳过？

**Comment by dataabc** [comment]
可能就是被ban了，如果是这样什么id都会出错，不能跳过。

**Comment by YummyToolman** [comment]
> 可能就是被ban了，如果是这样什么id都会出错，不能跳过。

感谢回复，不过确实是id出错了，每次都是我删掉下一个id之后可以正常继续运行，不过每次都需要手动删除非常麻烦，不知道如何实现id出错后跳过此id继续运行

**Comment by dataabc** [comment]
你可以先暂时使用weibospider，这个可以跳过。

**Comment by haozewu** [comment]
这个问题看起来已经解决，如果你有需要，可以reopen this issue。
