### ISSUE TITLE
新内容追加

### ISSUE THREAD

**Issue by haozewu** [dataabc/weibo-crawler#265]
#7定期自动爬取微博（可选）这部分的方法能追加的最小粒度得是”天“了，有些博主删微博太快，需要以更小粒度记录。

新内容追加可以建一个”记录特定用户id和对应最新微博id“的文件，然后每次更新追加内容都更新该文件。

config里可以加一个运行模式，例如overwrite模式或append模式。

- [x] （cookie失效）的消息推送，
- [x] 用微博id和日期共同标注上次微博。
- [ ] crontab自动运行脚本配置。

**Comment by dataabc** [comment]
感谢建议。这个建议很好，我理解你的意思应该是，每次运行，每个id只获取最新的微博，不是全部。不知道有没有理解对。我有时间再想想，目前想到的是如果每次运行获取的微博是上次获取的，是否还要更新。如果更新可能会造成重复；如果不更新，用户又编辑了微博，之前的内容就是旧的。我再想想。再次感谢建议。

**Comment by haozewu** [comment]
意思正是如此。

你提到的用户更新微博的情况确实是存在的，不过从用户习惯角度出发，更新时间通常在3天内，或者置顶微博。

这个特性我有时间就做一下，因为我准备用crontab每隔三个小时记录一次增量更新。

另外问一句，这个项目的代码为什么只有一个文件，而不是把方法拆分出来？是有什么特殊需要吗？

**Comment by dataabc** [comment]
一个文件是因为想让使用者“看起来更容易”，直接运行它就行。但这样确实不方便修改，改成多文件也可以。

**Comment by haozewu** [comment]
嗯。我新提的“追加保存微博功能”的pr拆成了多个文件，把非核心方法放到`util/`文件夹里面了。

现在距离预期目标“在服务器定期备份微博”就差个两个功能：
- （cookie失效）的消息推送，
- crontab自动运行脚本配置。

**Comment by dataabc** [comment]
感谢，已经merge了。已经发送了协作者邀请，接受后就可以直接提交代码了，如果不方便不接受也没关系，感谢热心的贡献。

**Comment by haozewu** [comment]
上次写的有bug，用户一删微博就又开始overwrite了。需要
- [ ] 用微博id和日期共同标注上次微博。
