### ISSUE TITLE
微博发布日期能否精确为秒

### ISSUE THREAD

**Issue by JackyWang925** [dataabc/weibo-crawler#270]
想要做时序分析  希望可以优化下┭┮﹏┭┮

**Comment by haozewu** [comment]
可以的。你自己把下面这一行中的`'%Y-%m-%d'`改成`'%Y-%m-%d %H:%M:%S'`就成了。

https://github.com/dataabc/weibo-crawler/blob/4bb8129b1ff9eb741bfcd7f131010e58ce811d90/weibo.py#L635

**Comment by JackyWang925** [comment]
> 可以的。你自己把下面这一行中的`'%Y-%m-%d'`改成`'%Y-%m-%d %H:%M:%S'`就成了。
> 
> https://github.com/dataabc/weibo-crawler/blob/4bb8129b1ff9eb741bfcd7f131010e58ce811d90/weibo.py#L635

感谢感谢~
