### ISSUE TITLE
cookie一直报错，：cookie错误或已过期,请按照README中方法重新获取

### ISSUE THREAD

**Issue by lwb58** [dataabc/weibo-crawler#283]
cookie已经设置了，但是不是按readme中的方法，因为https://passport.weibo.cn/signin/login；这个链接无法登录，一直提示url错误。

**Comment by dataabc** [comment]
可能cookie确实是不对的，cookie可以在weibospider运行看看。

**Comment by lwb58** [comment]
感谢回复，运行报错了，2022-04-17 22:30:21,589 - WARNING - info_parser.py[:24] - cookie错误或已过期,请按照README中方法重新获取，但是这个cookie是刚刚从微博主页的请求头里拿的啊，你给的链接我无法登录

**Comment by dataabc** [comment]
主页的cookie貌似不是通用的，还是需要有效cookie，否则会出错。

**Comment by lwb58** [comment]
可是按readme所示方法无法打开链接获取cookie欸

**Comment by lwb58** [comment]
edge问题，chrome就可以了
