### ISSUE TITLE
append模式在登记置顶微博后误将置顶微博当成最新微博

### ISSUE THREAD

**Issue by haozewu** [dataabc/weibo-crawler#289]
这样的后果是：若置顶不替换，则始终无法更新微博。

正在处理本问题。

**Comment by haozewu** [comment]
微博对于置顶内容呈现形式做了调整，导致是否为置顶检查失效。

**Comment by haozewu** [comment]
用了一种将就的方法，就是把所有用户的第一条微博都当成置顶。
先这样弄。

**Comment by banlangen1111** [comment]
确实是因为置顶微博的原因，没有置顶微博的微博账号都可以正常爬取，有置顶微博的都不可以，但是我按照您修改后的代码再次运行，还是没有获取到有置顶微博的微博用户所发布的微博信息。
