### ISSUE TITLE
argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by youaremywind** [dataabc/weibo-crawler#3]
<img width="434" alt="Screen Shot 2019-08-14 at 2 35 31 PM" src="https://user-images.githubusercontent.com/18423358/62999431-fa022480-bea0-11e9-9e3e-af649e2eca0b.png">

**Comment by dataabc** [comment]
感谢反馈，如果方便，能否提供目标微博id，方便调试

**Comment by youaremywind** [comment]
1721396755  本来想去你另一个项目把下载视频的也一起移植到这个项目 但是没找到视频的字段他好像是存在page_info里面 ；  还有一个问题就是有cookie 版的和这个版既然都可以爬 那岂不是这个版本更好

**Comment by dataabc** [comment]
现在，我已经把下载微博视频的功能加到这个项目了，如果发现有bug，欢迎反馈。
两者的区别在于，这个爬取的字段更多。coookie版的没有"话题"和"@用户"，转发微博中被转发的微博也只获取了部分重要信息。本程序获取的字段更多，有"话题"和"@用户"字段，转发微博中被转发的微博信息除了不包含"转发微博"外，其它和原创微博一样，获取的信息非常全。还有，本程序获取的用户信息也更全。
因为，大部分微博可以免登录查看，如<https://m.weibo.cn/detail/4403025562890184>,少量微博需要登录才能查看，如<https://m.weibo.cn/detail/4402254083394033>，所以这部分微博在没有cookie的情况下无法获取。所以cookie版虽然获取的字段少，但却可以获取全部微博。因为需要登录才可以看的微博很少，大约%5左右，这个百分比不一定准，所以免cookie可以得到95%左右的微博。如果想要得到全部微博，可以在本程序中添加cookie，具体可以参考cookie版，修改后就可以获得全部微博，而且获取的字段也比另一个项目多。事实上，两者的cookie是可以通用的。因为本程序的主旨是免cookie，所以没有添加cookie。

**Comment by youaremywind** [comment]
好的谢谢

**Comment by dataabc** [comment]
问题已修复，出错原因是有一条转发微博的被转发微博被作者设置成了“仅展示半年内微博”，微博虽然存在，但是对用户和程序都是不可见的，导致获取失败。现在程序改成了不可见的内容赋值为''，可见部分正常获取。
