### ISSUE TITLE
新版本仍然有部分微博用户出现爬取0条的问题

### ISSUE THREAD

**Issue by banlangen1111** [dataabc/weibo-crawler#301]
![image](https://user-images.githubusercontent.com/63344963/169834917-de75e33d-ce73-4062-8ef9-d4e823d720c8.png)

**Comment by banlangen1111** [comment]
问题仍然出现在置顶微博的判断失效上

**Comment by banlangen1111** [comment]
我参考上次提问过的这个问题的回答者haozewu可能是碰到了置顶微博
参考 https://github.com/dataabc/weibo-crawler/issues/289#issue-1213069764

仿照此修改正常模式下的置顶微博判断，但是可能是我代码修改不正确的原因，这个方法并不奏效

**Comment by banlangen1111** [comment]
后来我找到了一种暂时避过这个问题的办法
总体思想是，先确定该置顶微博的日期，定义一个变量top=0以标志这条置顶微博，当碰到置顶微博时(一般情况下置顶微博的发布时间会比爬取时间小，且此时top=1)，此时将top修改为1，下一次判断是top已不为0，因此后面所有小于since_date的微博都不会再爬取

**Comment by banlangen1111** [comment]
![image](https://user-images.githubusercontent.com/63344963/169853089-63ec543c-5b31-4976-a008-7f0a64fce61b.png)

**Comment by banlangen1111** [comment]
![image](https://user-images.githubusercontent.com/63344963/169853958-26ab87c6-0cfb-401b-b694-2e01ab795011.png)

**Comment by dididudu998** [comment]
> 后来我找到了一种暂时避过这个问题的办法 总体思想是，先确定该置顶微博的日期，定义一个变量（比该日期小一天）定义一个变量top=0以标志这条置顶微博，当碰到置顶微博时(一般情况下置顶微博的发布时间会比爬取时间小，且此时top=1)，此时将top修改为1，下一次判断是top已不为0，因此后面所有小于since_date的微博都不会再爬取
-----
这个方法不错。确实解决了问题。

**Comment by gaelthas** [comment]
有些用户有多条置顶微博
![image](https://user-images.githubusercontent.com/11371061/173168403-f1808e2b-fe9c-4f95-8abc-c5b10e4a3f38.png)

**Comment by gaelthas** [comment]
网页接口中看到有isTop字段，目前接口无数据，我改了新接口，已提交pr
