### ISSUE TITLE
weibo.py运行了很久（10分钟左右）报错

### ISSUE THREAD

**Issue by zhaozilong2zl** [dataabc/weibo-crawler#313]
作者您好！在运行weibo.py后，程序运行了大概10分钟（只爬一个用户）后弹出报错且未生成结果文件，但是仍然显示信息抓取完毕，部分报错信息如下：HTTPSConnectionPool(host='m.weibo.cn', port=443): Max retries exceeded with url: /api/container/getIndex?containerid=1005057766160338 (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)'))))

**Comment by zouzili311** [comment]
关掉梯子就可以爬了，但是十分慢

**Comment by DYH-Devil** [comment]
用这个必须关掉梯子的，不然用不了
