### ISSUE TITLE
求问如何修改mysql的字段

### ISSUE THREAD

**Issue by gujiwuqing** [dataabc/weibo-crawler#317]
因为存储的数据量比较大，然后只想保存几个字段到数据库里面，所以想咨询如何去除几个不需要的字段，在weibo.py 生成sql语句中直接去除那几个字段貌似会报错的样子

**Comment by dataabc** [comment]
这需要修改创建mysql和插入mysql的方法，保留你需要的字段。

**Comment by gujiwuqing** [comment]
> 这需要修改创建mysql和插入mysql的方法，保留你需要的字段。

好的 我试试
