### ISSUE TITLE
请求增加视频页面链接的保存

### ISSUE THREAD

**Issue by SingleRottenChips** [dataabc/weibo-crawler#326]
众所周知，微博可以通过在正文中输入视频页面链接以转载视频，包括半年以前不可见的视频。

另外请问有哪位大佬知道用源视频url打开视频的方法吗？现在用url打开视频都会报403. 我发现图片可以通过输入链接到微博正文中发布，再通过一个微博转链打开；然而视频链接无法输入正文。 事实上我也不确定未来图片链接是否也会被禁止输入到正文中... 所以有什么稳定而且更方便的方法吗？

多谢！

**Comment by dataabc** [comment]
感谢反馈。目前没有修改代码的打算，但是你可以在代码中找到视频相关的，应该有链接，只是没有保存，仿造其它字段保存即可。403错误应该是视频链接有有效期，过一段时间就失效了可能，这个我也没有好的办法。

**Comment by SingleRottenChips** [comment]
> 感谢反馈。目前没有修改代码的打算，但是你可以在代码中找到视频相关的，应该有链接，只是没有保存，仿造其它字段保存即可。403错误应该是视频链接有有效期，过一段时间就失效了可能，这个我也没有好的办法。

感谢回复。我回去好好研究一下…… 视频链接确实有时效，这个我之前也发现了。但不知是我个人问题还是如何，我无法通过 url 直接打开任何微博的图片和视频(无论时限)，全都会报403错误，除非通过发布微博或评论得到一个转链(t.cn 或 weibo.cn/sinaurl).
