### ISSUE TITLE
windows下如何运行程序

### ISSUE THREAD

**Issue by Alpenl** [dataabc/weibo-crawler#330]
纯小白实在不知道怎么搞，我把weibo.py拖入cmd后pychar会直接打开.py文件。。。。
求大佬讲解

**Comment by dataabc** [comment]
你可以先把安装个命令行工具，然后在本程序文件夹下右键打开命令行工具，运行python3 weibo.py。

**Comment by Alpenl** [comment]
感谢，马上尝试

**Comment by Alpenl** [comment]
已解决，感谢大佬
