### ISSUE TITLE
修改爬取间隔设定改哪个位置？

### ISSUE THREAD

**Issue by lisicheng1997** [dataabc/weibo-crawler#379]
之前在问题里有看到过大佬说改某处间隔可以增快爬取速度，但是现在忘记也没翻到

**Comment by dataabc** [comment]
程序是通过sleep暂停的，直接搜索它在程序的位置即可。

**Comment by lisicheng1997** [comment]
收到，之前是看到人家设置了一个很小的间隔 我寻思用他那个数值
