### ISSUE TITLE
希望增添 since_date 对时间的支持

### ISSUE THREAD

**Issue by plutonji** [dataabc/weibo-crawler#396]
目前since_date只能填写日期，精确到天。使用场景上来说，我如果一天内要多次爬取，可能就会发生重复爬取上一次爬取过的当天内容，因此希望能添加对更精确的时间支持，如 weibo-spider 一样。

**Comment by dataabc** [comment]
目前我不方便添加这个，不过思路很简单，您可以自己实现。比如是日期时，可以转化为这个日期的0点0分，然后和微博时间比较。
