### ISSUE TITLE
你好，user id list无法正常读取

### ISSUE THREAD

**Issue by LuciaLujia** [dataabc/weibo-crawler#41]
你好，我尝试把id都放在新建的txt文档里，但是分别遇到了两次错误
1. 按照readme里面每行一个id，id后面加空格再加注释（可选）的方式，显示utfcode无法解码（Error:  'utf-8' codec can't decode byte 0xc0 in position 13: invalid start byte）。
2. 去掉注释和空格以后，每行留一个id，只能爬第一个id，然后显示Error:  'nickname'
请问可以帮忙解答一下是什么原因吗？
非常感谢这个项目及解答！

**Comment by dataabc** [comment]
感谢反馈。怀疑是user_id_list txt文档编码格式有问题。
大部分txt文档都是采用utf-8编码，少部分采用其它编码。程序对这些编码都作了处理，一般来说可以正确读取文件。但是txt文件也有可能被设置成了本程序还没有考虑过的编码，因此出现问题。
如果是这种情况，可以通过文本编辑器把user_id_list文档的编码设置成utf-8，问题就解决了。

如果问题还没解决并且你方便的话，能否提供出错的user_id_list文件，方便调试，谢谢。

**Comment by LuciaLujia** [comment]
谢谢回复！将原先的文件编码改成utf-8就正常了。检查了一下，之前报错的编码是ANSI。再次感谢~

**Comment by LuciaLujia** [comment]
更新一下情况，对新下载的weibo.py，现在变成每行只有一个id的情况会报错（Error: 'nickname'），id+空格+几个中文字的情况就不会报错。其他编码之类的格式都是一样的。暂时没发现是什么问题，我先把所有id后面都随便加了几个字解决..

**Comment by dataabc** [comment]
感谢反馈，问题已经修复。

原因是字段名写错了，不是nickname而是screen_name，所以出错。将字段名字修改正确就解决这个问题了。

再次感谢
