### ISSUE TITLE
如果是长微博出现'全文'字样爬取不全

### ISSUE THREAD

**Issue by HanchuQin** [dataabc/weibo-crawler#413]
https://i.imgur.com/qfTWY3H.png

**Comment by HanchuQin** [comment]
![pycharm64_Dzp1rWMZdm](https://github.com/dataabc/weibo-crawler/assets/42774905/a102030a-34ec-4f09-956d-96b815d630e3)

**Comment by dataabc** [comment]
感谢反馈。可能是网页格式改变了，导致全文无法全部获取，我现在不方便调试，可能要过一段时间才能修改。

**Comment by HanchuQin** [comment]
> 感谢反馈。可能是网页格式改变了，导致全文无法全部获取，我现在不方便调试，可能要过一段时间才能修改。

大佬是我错了，debug走了一下，发现是cookie过期了，导致get_long_weibo方法拿不到长微博的html。
