### ISSUE TITLE
求助-爬微博进度100%，但是数量明显跟实际数量不一致有可能是何原因？

### ISSUE THREAD

**Issue by wendywjhu** [dataabc/weibo-crawler#424]
<img width="305" alt="image" src="https://github.com/dataabc/weibo-crawler/assets/8196802/7511396f-287b-47dc-a99b-4b198aafd11f">

在执行过程中，还有一个日志是写入MYSQL的日志，那个日志看着数量级是对的，但是最终落入MYSQL的数量不对。

**Comment by dataabc** [comment]
有可能是之前部分微博已经写入数据库了，程序只将数据库没有的内容写入，所以数量会少。

**Comment by wendywjhu** [comment]
解决了，是cookie的原因。
