### ISSUE TITLE
用id1669879400试写mysql数据库时报错

### ISSUE THREAD

**Issue by LuciaLujia** [dataabc/weibo-crawler#43]
你好，报错为：pymysql.err.DataError: (1406, "Data too long for column 'at_users' at row 1")

这里数据库小白一枚..查了一下网上说有可能是数据库的编码问题。我看了一下mysql的编码如下（server的编码也是utf8mb4），不知道具体哪个值的编码应该再进行调整。麻烦你方便的时候帮忙看一下~谢谢！！
![屏幕截图(24)](https://user-images.githubusercontent.com/49893048/75321704-4eed1180-58ac-11ea-8575-118d080a4461.png)

**Comment by LuciaLujia** [comment]
改了at_users varchar(500)就可以啦 谢谢~

**Comment by dataabc** [comment]
感谢反馈，问题已经修复。

出错的原因是微博艾特了很多用户，导致at_users很长，比数据库中定义的长度长，因此增加这个字段的长度就可以解决问题。考虑到很多微博可能艾特很多用户，因此把长度设成了1000。

再次感谢热心反馈，不但发现了问题，还能反馈解决方法，非常热心，感谢:smile:

**Comment by LuciaLujia** [comment]
不客气 感谢你的代码 帮我解决了毕业论文的数据问题哈哈哈
