### ISSUE TITLE
since_date 格式不正确，请确认配置是否正确

### ISSUE THREAD

**Issue by wangmengbin1** [dataabc/weibo-crawler#437]
麻烦帮忙看一下是哪里有配置的不对吗

![Uploading 11.png…]()

**Comment by wangmengbin1** [comment]
输入的整数1但是报这个错误

**Comment by dataabc** [comment]
如果是整数，数字两边不能有引号。

**Comment by wangmengbin1** [comment]
> 如果是整数，数字两边不能有引号。

是没有引号的

**Comment by dataabc** [comment]
换成日期能运行吗？

**Comment by wangmengbin1** [comment]
不太行，我重新拉下项目试一下，如果user文件里边每行后边没有日期应该不会影响吧

**Comment by wangmengbin1** [comment]
重新拉了下项目运行了一下可以了，然后我又运行了一下之前的那个也可以了不知道什么原因
