### ISSUE TITLE
运行之后总是显示config.json格式不正确

### ISSUE THREAD

**Issue by Lzcns** [dataabc/weibo-crawler#445]
麻烦问下，按照说明设置好config.json文件后再运行，总是显示这个提示。能帮忙看看是哪里不对么？
{
    "user_id_list": ["2453184077"],
    "only_crawl_original": 1,
    "since_date": “2024-06-01”,
    "start_page": 1,
    "write_mode": ["csv"],
    "original_pic_download": 1,
    "retweet_pic_download": 0,
    "original_video_download": 0,
    "retweet_video_download": 0,
    "download_comment": 0,
    "comment_max_download_count": 10,
    "download_repost": 0,
    "repost_max_download_count": 10,
    "user_id_as_folder_name": 0,
    "remove_html_tag": 1,
    "cookie": "your cookie",
    "post_config": {
        "api_url": "https://api.example.com",
        "api_token": ""
    }
}

**Comment by dataabc** [comment]
since_date后的日期应该使用英文的双引号。

**Comment by Lzcns** [comment]
多谢解答，可以正常运行了，囧，我竟然没看出来这个错误
