### ISSUE TITLE
为什么新添加的几个信息，生日、注册日期、阳光信用什么的都是空白呢？

### ISSUE THREAD

**Issue by MiaCompiling** [dataabc/weibo-crawler#61]

**Comment by MiaCompiling** [comment]
![image](https://user-images.githubusercontent.com/59831989/77058447-6a14f200-6a10-11ea-9599-cf4f0f931d1e.png)

**Comment by dataabc** [comment]
这些字段需要有cookie才可以获取，把有效cookie填到config.json对应位置就可以获取这些值了

**Comment by MiaCompiling** [comment]
好的明白了，谢谢！
