### ISSUE TITLE
这个函数看不太懂，请求讲解一下

### ISSUE THREAD

**Issue by MiaCompiling** [dataabc/weibo-crawler#62]
![image](https://user-images.githubusercontent.com/59831989/77058991-34bcd400-6a11-11ea-9cd1-c88e6c7d75df.png)

**Comment by dataabc** [comment]
这个函数就是访问网页然后返回字典格式的数据，微博的所有内容都在里面。url是基础链接，params包含要访问网页的具体参数，url和params加起来才是完整的链接，大致就这个意思

**Comment by MiaCompiling** [comment]
这个字典格式的数据是微博提供的吗？为什么不能直接自己创建相同的一个字典呢？

**Comment by dataabc** [comment]
是微博提供的。直接解析它就能获得微博信息，因为该字典有很多不明所以的字段，所以只保留了其中有用的信息

**Comment by MiaCompiling** [comment]
明白了，太感谢了！
