### ISSUE TITLE
请问这个函数倒数第二行的encode, decode是在实现什么功能？

### ISSUE THREAD

**Issue by MiaCompiling** [dataabc/weibo-crawler#63]
![image](https://user-images.githubusercontent.com/59831989/77216530-e402c380-6b55-11ea-8ae6-547c06e78f6b.png)

**Comment by dataabc** [comment]
去除非法字符，如果不去除，会可能导致很多错误，如打印错误，写入文件错误等。首先用encode编码通过ignore过滤非法字符，再通过decode解码

**Comment by MiaCompiling** [comment]
那为什么要单独把/u200b拿出来删掉呢？

**Comment by dataabc** [comment]
因为/u200b用上面的方法忽略不掉，要手动去除

**Comment by MiaCompiling** [comment]
哦哦明白了，谢谢！
