### ISSUE TITLE
请问这几行是在干什么？我调试看了看结果，发现这几行执行过程中并没有什么变化啊？

### ISSUE THREAD

**Issue by MiaCompiling** [dataabc/weibo-crawler#64]
![image](https://user-images.githubusercontent.com/59831989/77228833-01bb4180-6bc5-11ea-99d6-81c5116839b3.png)

**Comment by dataabc** [comment]
作用是获取微博信息。

这里的html是长微博的详情页面。里面包含html代码和微博的json信息，两种混在一起。上面的代码是先去除html信息，留下weibo的json格式的信息，然后就可以提取微博信息了

**Comment by MiaCompiling** [comment]
哦哦这样啊，可是这个网站url = 'https://m.weibo.cn/detail/%s' % id里要怎么才能找到这个文档呢？我找了很久也没看见
![image](https://user-images.githubusercontent.com/59831989/77240334-c568ff00-6c1f-11ea-9a4f-7125251a532e.png)

**Comment by dataabc** [comment]
查看网页源代码就可以了，上面就是解析的网页源代码

**Comment by MiaCompiling** [comment]
![image](https://user-images.githubusercontent.com/59831989/77241451-437fd280-6c2d-11ea-85fa-b38f5137e6f8.png)

**Comment by dataabc** [comment]
在网页上右键单击，点击“查看网页源代码”即可

**Comment by MiaCompiling** [comment]
哦哦谢谢！！找到了
