### ISSUE TITLE
请问为什么这么多这个错误啊？

### ISSUE THREAD

**Issue by MiaCompiling** [dataabc/weibo-crawler#67]
![image](https://user-images.githubusercontent.com/59831989/77408573-e59ce780-6df2-11ea-99eb-a392b07f1184.png)

**Comment by dataabc** [comment]
你是不是修改cookie相关的代码了？
应该这样写
```
requests.get(url, cookies=xxx)
```
是不是把cookies写成cookie了

**Comment by MiaCompiling** [comment]
确实确实，谢谢！
