### ISSUE TITLE
pymysql配置完成后，无法写入数据库

### ISSUE THREAD

**Issue by PFpengfeng** [dataabc/weibo-crawler#69]
错误如下，请求帮忙解决
尝试用pymysql登录数据库，数据库配置正常

![image](https://user-images.githubusercontent.com/57736376/77429543-c911a700-6e14-11ea-9bf2-33d3692c8b84.png)

**Comment by dataabc** [comment]
如果config.json中关于mysql的配置都正确，怀疑可能是mysql的配置问题，为了安全问题，一些版本的mysql不允许用root这样写数据，需要修改相关mysql配置才可以。你可以把mysql_create_database方法中的try......except相关语句注释掉，看看具体有什么错误，再根据提示信息搜索下解决方案
