### ISSUE TITLE
超字数的微博无法爬取全文

### ISSUE THREAD

**Issue by passonce** [dataabc/weibo-crawler#70]
若原微博超过140字，爬取结果末尾直接显示“ ...全文”。可否增加爬取全文的功能，或可否像获取超链接那样通过简单设置爬取全文？

**Comment by dataabc** [comment]
感谢反馈，可以获取全文。

程序的思路是在微博列表页遇到长微博（上面显示不全的微博）时，先暂时保存这个不完整的内容，然后去该微博详情页获取详细内容。这时候有两种情况，获取成功和获取失败。如果成功就用完整内容替代不完整内容，否则就使用不完整的内容，获取不全毕竟比获取不到要好。
get_long_weibo方法是控制获取长微博的，为了避免卡在一条微博上，尝试获取5次长内容，如果5次都获取失败就使用不全的内容。如果你一定要获取长微博，可以把for循环改成while。

**Comment by passonce** [comment]
明白了，谢谢你的耐心回复。我再试试。

**Comment by lyle-luan** [comment]
我看了下get_long_weibo中的链接，我给改成https://m.weibo.cn/status/%s，我试试能不能行。

**Comment by lyle-luan** [comment]
url改成status后，大多数都能爬下来了。

**Comment by dataabc** [comment]
> url改成status后，大多数都能爬下来了。

感谢建议。改成status后比之前更容易获取长微博全文吗？因为它们都是在单独的页面获取信息的，不知道是偶然现象还是status更好。再次感谢反馈。
