### ISSUE TITLE
请教:如何限制获取用户信息的速度

### ISSUE THREAD

**Issue by xm634634** [dataabc/weibo-crawler#76]
用户信息
Error:  'id'
Traceback (most recent call last):
  File "weibo.py", line 983, in get_pages
    self.print_user_info()
  File "weibo.py", line 510, in print_user_info
    print(u'用户id：%s' % self.user['id'])
KeyError: 'id'
信息抓取完毕
****************************************************************************************************
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
用户信息
Error:  'id'
Traceback (most recent call last):
  File "weibo.py", line 983, in get_pages
    self.print_user_info()
  File "weibo.py", line 510, in print_user_info
    print(u'用户id：%s' % self.user['id'])
KeyError: 'id'
信息抓取完毕
****************************************************************************************************
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
用户信息
Error:  'id'
Traceback (most recent call last):
  File "weibo.py", line 983, in get_pages
    self.print_user_info()
  File "weibo.py", line 510, in print_user_info
    print(u'用户id：%s' % self.user['id'])
KeyError: 'id'
信息抓取完毕
****************************************************************************************************
Error:  'screen_name'
Traceback (most recent call last):
  File "weibo.py", line 1056, in start
    self.update_user_config_file(self.user_config_file_path)
  File "weibo.py", line 947, in update_user_config_file
    info.append(self.user['screen_name'])
KeyError: 'screen_name'

**Comment by dataabc** [comment]
修改start方法，每一次循环就是获取一个用户，可以在每个循环后随机sleep

**Comment by xm634634** [comment]
> 修改start方法，每一次循环就是获取一个用户，可以在每个循环后随机sleep

        """运行爬虫"""
        try:
            for user_config in self.user_config_list:
                self.initialize_info(user_config)
                self.get_pages()
                print(u'信息抓取完毕')
                print('*' * 100)
                if self.user_config_file_path:
                    self.update_user_config_file(self.user_config_file_path)
        except Exception as e:
            print('Error: ', e)
            traceback.print_exc()
        sleep(random.randint(6, 10))

**Comment by dataabc** [comment]
def start(self):
        """运行爬虫"""
        try:
            for user_config in self.user_config_list:
                self.initialize_info(user_config)
                self.get_pages()
                print(u'信息抓取完毕')
                print('*' * 100)
                if self.user_config_file_path:
                    self.update_user_config_file(self.user_config_file_path)
                sleep(random.randint(6, 10))
        except Exception as e:
            print('Error: ', e)
            traceback.print_exc()

**Comment by xm634634** [comment]
之前放在        """获取用户信息"""
死活不生效，这是为什么？

程序内的        """获取长微博"""
        for i in range(5):
            url = 'https://m.weibo.cn/detail/%s' % id
            html = requests.get(url, cookies=self.cookie).text
            html = html[html.find('"status":'):]
            html = html[:html.rfind('"hotScheme"')]
            html = html[:html.rfind(',')]
            html = '{' + html + '}'
            js = json.loads(html, strict=False)
            weibo_info = js.get('status')
            if weibo_info:
                weibo = self.parse_weibo(weibo_info)
                return weibo
            sleep(random.randint(6, 10))
为啥就生效了

**Comment by xm634634** [comment]
> ```
> def start(self):
>     """运行爬虫"""
>     try:
>         for user_config in self.user_config_list:
>             self.initialize_info(user_config)
>             self.get_pages()
>             print(u'信息抓取完毕')
>             print('*' * 100)
>             if self.user_config_file_path:
>                 self.update_user_config_file(self.user_config_file_path)
>             sleep(random.randint(6, 10))
>     except Exception as e:
>         print('Error: ', e)
>         traceback.print_exc()
> ```

非常感谢，但不知道为啥，我的写法也生效了…噗哈哈哈

**Comment by dataabc** [comment]
你那样写是获取所有用户后再sleep，应该在获取一个用户后sleep，在获取用户里写应该也是可以的。

**Comment by xm634634** [comment]
> 你那样写是获取所有用户后再sleep，应该在获取一个用户后sleep，在获取用户信息里写应该也是可以的。

在获取用户信息最后一行添加sleep，3次均以失败告终，捂脸
