### ISSUE TITLE
 您好，since_date好像有点问题

### ISSUE THREAD

**Issue by zytjs** [dataabc/weibo-crawler#82]
设置了最新since_date后爬取，总是会先爬取上一次设置的时间，第二次爬取才是最新设置的时间。

比如：设置了今天"2020-04-28"，它会按“2020-04-27”先爬取一遍，第二次爬取才是"2020-04-28"的内容。

测试好像是user_id_list.txt后面时间的影响
![image](https://user-images.githubusercontent.com/12710516/80475474-8004c380-897b-11ea-8d06-880458f14873.png)

**Comment by dataabc** [comment]
感谢反馈，测试了下，没有复现问题。

你的since_date是在config.json设置的吗？程序默认使用config.json中的since_date，如果你使用txt输入user_id，则使用txt中的时间。

这样的好处是：
1.可以对不同的user_id设置不同的since_date，比如你新增了一个用户，你想爬它的全部微博。如果在config.json中设置，那其它user_id也会再重新爬一遍。在txt中设置可以只爬取该用户的微博，其它的不影响；
2.不用关心since_date，增量爬取。在config.json设置，如果想爬取某写用户的新微博，需要手动设置since_date;现在通过txt设置since_date，程序会自动更新since_date，日期为上一次开始执行的时间。这样下次程序会执行到上次的时间为止，省时省力。

**Comment by zytjs** [comment]
我用的txt，他是怎么自动更新时间的？比如昨天爬完，后面是2020-04-27，我今天爬取的话，只能手动把TXT中的时间改为2020-04-28吧



---原始邮件---
发件人: "Chen Lei"<notifications@github.com&gt;
发送时间: 2020年4月28日(周二) 晚上7:21
收件人: "dataabc/weibo-crawler"<weibo-crawler@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"zytjs"<zhao1tong@qq.com&gt;;
主题: Re: [dataabc/weibo-crawler]  您好，since_date好像有点问题 (#82)




 
感谢反馈，测试了下，没有复现问题。
 
你的since_date是在config.json设置的吗？程序默认使用config.json中的since_date，如果你使用txt输入user_id，则使用txt中的时间。
 
这样的好处是：
 1.可以对不同的user_id设置不同的since_date，比如你新增了一个用户，你想爬它的全部微博。如果在config.json中设置，那其它user_id也会再重新爬一遍。在txt中设置可以只爬取该用户的微博，其它的不影响；
 2.不用关心since_date，增量爬取。在config.json设置，如果想爬取某写用户的新微博，需要手动设置since_date;现在通过txt设置since_date，程序会自动更新since_date，日期为上一次开始执行的时间。这样下次程序会执行到上次的时间为止，省时省力。

**Comment by dataabc** [comment]
时间是程序自动更新的，把程序执行时所在的日期在txt更新成since_date。2020-04-27执行就是2020-04-27，2020-04-28执行就是2020-04-28，下次程序执行到这个日期就停止了，并更新since_date

**Comment by zytjs** [comment]
OK，明白了，那这个增量更新是只精确到日吧？我看txt只精确到日



---原始邮件---
发件人: "Chen Lei"<notifications@github.com&gt;
发送时间: 2020年4月28日(周二) 晚上7:37
收件人: "dataabc/weibo-crawler"<weibo-crawler@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"zytjs"<zhao1tong@qq.com&gt;;
主题: Re: [dataabc/weibo-crawler]  您好，since_date好像有点问题 (#82)




 
时间是程序自动更新的，把程序执行时所在的日期在txt更新成since_date。2020-04-27执行就是2020-04-27，2020-04-28执行就是2020-04-28，下次程序执行到这个日期就停止了，并更新since_date

**Comment by zytjs** [comment]
但是，我今天把txt中的日期改为28号，爬完后还是28，明天再爬取，还是28，还得手动改为29的。

**Comment by dataabc** [comment]
> 但是，我今天把txt中的日期改为28号，爬完后还是28，明天再爬取，还是28，还得手动改为29的。

因为今天是2020-04-28，使用今天执行肯定是不能变成29啊，明天执行就是29，日期是执行的日期。

**Comment by zytjs** [comment]
明白了，感谢回复。
有没有办法，今天爬完让日期加1呢，因为明天肯定爬加1后的日期了。



---原始邮件---
发件人: "Chen Lei"<notifications@github.com&gt;
发送时间: 2020年4月28日(周二) 晚上10:23
收件人: "dataabc/weibo-crawler"<weibo-crawler@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"zytjs"<zhao1tong@qq.com&gt;;
主题: Re: [dataabc/weibo-crawler]  您好，since_date好像有点问题 (#82)




  
但是，我今天把txt中的日期改为28号，爬完后还是28，明天再爬取，还是28，还得手动改为29的。
  
因为今天是2020-04-28，使用今天执行肯定是不能变成29啊，明天执行就是29，日期是执行的日期。

**Comment by dataabc** [comment]
可以。

get_pages方法的如下语句
```
                self.start_date = datetime.now().strftime('%Y-%m-%d')
```
就是要写入的since_date，默认是今天，可以改成明天，不过这样如果某用户今天又发了新微博就不能获取了，因为since_date变成明天了

**Comment by zytjs** [comment]
感谢，我都是晚上爬取当天数据，所以正好是我想要的，再次感谢。



---原始邮件---
发件人: "Chen Lei"<notifications@github.com&gt;
发送时间: 2020年4月29日(周三) 凌晨0:00
收件人: "dataabc/weibo-crawler"<weibo-crawler@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"zytjs"<zhao1tong@qq.com&gt;;
主题: Re: [dataabc/weibo-crawler]  您好，since_date好像有点问题 (#82)




 
可以。
 
get_pages方法的如下语句
                 self.start_date = datetime.now().strftime('%Y-%m-%d')  
就是要写入的since_date，默认是今天，可以改成明天，不过这样如果某用户今天又发了新微博就不能获取了，因为since_date变成明天了
