### ISSUE TITLE
使用哪种开源协议？

### ISSUE THREAD

**Issue by zzbslayer** [dataabc/weibo-crawler#86]
我打算在自己项目中用到该项目，并进行一定的修改。请问该项目使用哪种开源协议？

**Comment by dataabc** [comment]
感谢反馈。

项目的目的是帮助一些个人微博使用者，他们大部分是基于兴趣或学习等原因，想要获取微博信息，本项目可以为他们节约一些时间。之所以没有写开源协议，是因为我也不知道用哪种。个人使用者基于兴趣、学习等非盈利目的是可以使用和修改本项目的，但是如果是用于盈利，我是没权利授权的，该权利应该属于微博发布者和微博。所以，如果你也是基于个人爱好等非盈利原因，可以使用和修改本项目，如果是想要用在盈利的项目，应该要得到微博的授权。

如果还有其它问题，欢迎继续反馈

**Comment by zzbslayer** [comment]
好的谢谢
