### ISSUE TITLE
您好，在安装依赖时出现Error2：No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by Wuxingxing-Megan** [dataabc/weibo-crawler#87]
您好，在安装依赖时出现Error2：No such file or directory: 'requirements.txt'，请问该如何解决呢？非常感谢！

**Comment by dataabc** [comment]
感谢反馈，应该在weibo-crawler文件夹下运行安装命令。出现上述错误，应该是在其它文件夹执行的属于出错，requirements.txt在weibo-crawler文件夹下，也应改目录下执行安装命令

**Comment by Wuxingxing-Megan** [comment]
谢谢作者您！！！完美解决啦！！❤️
