### ISSUE TITLE
关于微博视频

### ISSUE THREAD

**Issue by kou18n** [dataabc/weibo-crawler#88]
你好，请问用爬下来的视频url，放到下载工具里面下载视频的时候，一大部分403 Forbidden。小部分视频可以成功下载。有什么解决方案吗？谢谢。

**Comment by dataabc** [comment]
感谢反馈。

url是有有效期的，出现403可能是过期了。可以通过设置config.json中的original_video_download为1,让程序边获取边下载原创微博视频，转发微博视频同理。

**Comment by kou18n** [comment]
原来是有有效期的啊，感谢回复。

**Comment by kou18n** [comment]
还有一个小问题，如何实现特定内容的过滤，比如根据微博文本内容(csv正文那一列)过滤掉一些不需要的微博，不进行爬取，是不是需要修改get_one_page这个函数的过滤逻辑呢。希望作者后续可以加入这个功能，感谢！

**Comment by dataabc** [comment]
需要修改get_one_page方法，原来的部分
```
                                self.weibo.append(wb)
                                self.weibo_id_list.append(wb['id'])
                                self.got_count += 1
                                self.print_weibo(wb)
```
在此代码之前加判断，
```
                                if keyword not in wb['text']:
                                    self.weibo.append(wb)
                                    self.weibo_id_list.append(wb['id'])
                                    self.got_count += 1
                                    self.print_weibo(wb)
```
其中keyword为你要过滤的关键词，这样微博文本中如果包含该内容，就不会保存，你也可以根据其它方面过滤，比如文本长度、是否包含数字等，都可以根据需要修改

**Comment by kou18n** [comment]
感谢回复，太给力了，位置和代码都给了。我是需要加入有特定关键字的内容，还有就是需要只抓取有视频内容的微博。感谢问题已解决。
`
keyword_list = ['A','B','C','D']
if any(keyword in wb['text'] for keyword in keyword_list) and (wb['video_url'] != ""):
`
