### ISSUE TITLE
【疑问】请问 api/container/getIndex 这个接口是怎么扒出来的？

### ISSUE THREAD

**Issue by Arsenal591** [dataabc/weibo-crawler#90]
请问 `api/container/getIndex` 这个接口是怎么扒出来的？
因为我用 chrome dev tool 试图抓包的时候，没有看到与该 URL 相关的包。

**Comment by dataabc** [comment]
可能是你使用的地址不对，使用<https://m.weibo.cn/>，结合Chrome调试工具就可以得到

**Comment by Arsenal591** [comment]
OK，我之前用https://m.weibo.cn/profile/[user id]抓不到包，改用https://m.weibo.cn/u/[user id]之后就好了。

**Comment by Arsenal591** [comment]
OK，我之前是使用https://m.weibo.cn/profile/USERID，这个地址应该用的是另外的API，使用https://m.weibo.cn/u/USERID就可以了

**Comment by Arsenal591** [comment]
OK，我之前是使用https://m.weibo.cn/profile/USERID，这个地址应该用的是另外的API，使用https://m.weibo.cn/u/USERID就可以了

**Comment by Pythondog3** [comment]
牛 解决了我的困惑
