### ISSUE TITLE
检测Cookie的方法是否无效？

### ISSUE THREAD

**Issue by gudaocode** [dataabc/weibo-crawler#94]
我按照方法二，把cookie设置好，然后将时间范围设置为“1”，即最近一天的内容。
运行，没有提示cookie错误。

再次进入配置文件，把cookie那一大长串的字符随便删除了几个（是不是这样应该就不好用了？），然后再次运行，依旧没有提示错误……

哦，为了便于找到是否有错误提示，运行时用了-i的参数

**Comment by gudaost** [comment]
另外，之前看到有人反馈说超过9张图片的微博，如果不用cookie，可能会出现无法找到全部图片的情况，是否可以把检测cookie的方式做成这种：
您在自己的微博中，或者独立的微博账号中建立一条，且附上去大于8张图片，然后看能够读取到几个图片链接/数量，等于8就是没成功，大于8应该是cookie没问题？
不知道是否可行，仅供参考

**Comment by dataabc** [comment]
感谢建议。

cookie是有很多字段组成的，只要包含部分必需的内容就可以验证成功，为了简化使用，没有区分哪些是必需的，只要按照说明，获取cookie就可以登录成功。所以，如果说删除一些字符，只要不是必需的内容，都是可以登录的。

另外，不登录，也可以获取9张图片，可以参考<https://m.weibo.cn/detail/4484272872327898>，在不登录的情况下，也可以看到9张图片。本项目是如果图片小于等于9张，可以全部获取，如果大于9张，只能获取9张。如果想要获取全部图片，可以使用<https://github.com/dataabc/weiboSpider>，该项目可以获取全部图片，不管是否大于9张。

感谢热心建议，如果还有其它问题或建议欢迎讨论，再次感谢。

**Comment by haozewu** [comment]
README上面写的Cookie的检测方法测了下，确实不好使。

**Comment by haozewu** [comment]
Cookie检查的逻辑是，使用cookie来源账号发布限定范围的微博，若cookie可用，则可以读取到，否则读取不到。

### 操作方法
使用cookie的来源账号发布一条微博，该账号和微博需要满足以下条件：
- 该微博需要是**非公开可见**
- 该微博需要是最近5条微博，不能后续发很多新微博
- 在`config.json`配置中的since_date之后，该账号必须有大于9条微博

然后将`const.py`文件中`'CHECK': False`中的`False`改为`True`，`'HIDDEN_WEIBO': '微博内容'`中的`微博内容`改为你发的限定范围的微博。

---
回头改改文档，原来的方法都不好使就全删了。

**Comment by haozewu** [comment]
你如果有需要可以试一下更新后的，如果你有什么问题可以reopen这个issue。
